# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SPUR
email: sehejpahujaa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  There are innumerable things in life which inspire us to keep us going. I will write about people, places, things and their stories. Stories that motivate me to be positive, teach me and help me grow into a better person everyday. Every individual, big or small, has a story to say. Every action, every reaction, every smile, every tear has somethings hidden. Some stories light up your face with awe while others get you to face gruesome reality.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sehejpahujaa
github_username:  sehejpahujaa
google_analytics: UA-115972691-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
